### ISSUE TITLE
ng-quill not working fully in Meteor App

### ISSUE THREAD

**Issue by cmitcoe** [KillerCodeMonkey/ng-quill#92] opened 2017-02-14 05:12 UTC
Hi @KillerCodeMonkey ,

This is the new thread for the discussion on technical issue we are facing in our meteor app. 

We are using ng-quill 2.1.0 in our meteor app.

the error we are getting is as below : 

![ngquill1](https://cloud.githubusercontent.com/assets/25744751/22916038/a5a91506-f2a1-11e6-9a39-065f81db5a22.PNG)

Hence the text editor is not functional in the UI. 
![ngquill](https://cloud.githubusercontent.com/assets/25744751/22916047/bef30404-f2a1-11e6-877c-41cdb8728528.PNG)

Below are the source code details -

import ngQuill from "ng-quill";

    var toolbarModules = ['bold', 'italic', 'underline', 'blockquote', 'link', 'image', { 'header': 1 }, { 'header': 2 }, { 'list': 'ordered' }, { 'list': 'bullet' }, { 'align': [] }, 'code-block'];
    var toolbarFormats = ['bold', 'italic', 'underline', 'blockquote', 'link', 'image', 'header', 'list', 'code-block', 'align'];
    ngQuillConfigProvider.set({
        toolbar: toolbarModules
    }, 'snow', 'placeholder', toolbarFormats);

The HTML Code is as below -

`<ng-quill-editor class="textEditor mbot16" ng-model="vraaag" on-content-changed="updateVraag(editor,'explaination.vraag',questionObjectId)" toolbar="true" link-tooltip="true" placeholder="Insert your text here" image-tooltip="true" flex></ng-quill-editor>
`

Versions used are -

ng-quill - 2.1.0
quill -1.1.9

Hope this information can help out figuring the issue. 

Thanks in advance.

**Comment by KillerCodeMonkey** [comment] 2017-02-14 07:15
not really...

because you do not see the correct place of the javascript error in production build... try to test the app without minified version or create sourcemaps to figure out what the problem is...

it could be that the error has nothing to do with ngquill and is part of your own code. So i will close this issue again, but will maybe answer on your question...

only thing i noticed: 
```
on-content-changed="updateVraag(editor, 'explaination.vraag', questionObjectId)"
```

Do not know why `explaination.vraag` is wrapped in single quotes and you should not rename or change the call of your update function.

You should use the callback of `on-content-changed` like shown in the readme:
`on-content-changed="myCallbackFunctionName(editor, html, text)"`

Angular works in this way, that the parameters editor, html, text should be named exactly this way, if you want additional parameters add them to this three.

Please let the developers debug the project in a correct way... i am not here to help you with build problems... check your commit history and your build process.

i think it is not my or a ng-quill problem if it working before without any changes and if it working on local machine.

Check out your tabsCtrl and part of html code provided in the error message. bye

**Closed by KillerCodeMonkey** 2017-02-14 07:15 UTC
